### ISSUE TITLE
SSR and Solid Start considerations

### ISSUE THREAD

**Issue by davedbase** [diragb/solid-custom-scrollbars#1]
Hi there! Love seeing a scrollbars utility for Solid, thanks for working on this! It will be very useful.

I'm wondering if it will support SSR. I think that the exports will need to be adjusted to support ESM & CJS to make that happen. Also using this in SolidStart (our meta framework) might be a bit wonky as we require a custom JSX export. We like to suggest use of [rollup-preset-solid](https://github.com/amoutonbrady/rollup-preset-solid) which will make exporting the various types much easier.

This should correct any SSR related a user might have :-)

Oh also you should submit this to our website resources list. Just submit a PR here to add it: https://github.com/solidjs/solid-site/blob/main/src/pages/Resources/Utilities.data.ts

**Comment by diragb** [comment]
Hey, thank you for the feedback and suggestions!
Honestly, I'm a bit confused about the export and bundling part. I'll be going through the resources you mentioned.

Additionally, I checked out your package [```solid-slider```](https://github.com/davedbase/solid-slider) (which I daresay, is pretty _solid_.. sorry, I had to do it), would you mind if I looked into it and copied over some of the configuration? Would you actually recommend it?

Please let me know if you have any other suggestions! 💙
